feat: tasks MUB
xi-effect/xi.back-2 pull request #12
Opened 2024-06-18 18:21 UTC by kinuser

2024-06-18 21:05 UTC, max31ru12 requested changes
Классное решение задачи, немного правок и папа будет доволен)

2024-06-18 21:05 UTC, max31ru12 commented on app/communities/routes/tasks_mub.py
> +    return tasks
question: Что-то я не понял задумку пагинации. Разве это реализуется не через query params? (Я, если что, не в курсе, как правильно писать эндпоинт для пагинации, но этот меня смущает)

2024-06-19 10:22 UTC, max31ru12 commented on app/communities/dependencies/tasks_dep.py
> +    community: CommunityById,
suggestion: Может сразу передавать community_id, а не весь объект? Как будто лишняя логика

2024-06-19 10:24 UTC, max31ru12 commented on app/communities/dependencies/tasks_dep.py
> +async def get_tasks_by_community_id(community: CommunityById) -> Sequence[Task]:
suggestion: Может сразу передавать community_id, а не весь объект? Как будто лишняя логика

2024-06-19 10:24 UTC, max31ru12 commented on app/communities/dependencies/tasks_dep.py
> +    community: CommunityById,
suggestion: Аналогично: передавать community_id, а не объект

2024-06-19 10:32 UTC, max31ru12 commented on app/communities/models/tasks_db.py
> +    WRITING = "writing"
issue: WRITING - очень неконкретное название для типа таски. например, это эссе или это письмо?

2024-06-19 10:37 UTC, max31ru12 commented on app/communities/models/tasks_db.py
> +            stmt.order_by(cls.creation_date)
issue: `TaskOrdering.CLOSING_DATE == "closing_date"` вернет False.

suggestion: А вот `TaskOrdering.CLOSING_DATE.value == "closing_date"` вернет True.

2024-06-19 10:55 UTC, max31ru12 commented on app/communities/routes/tasks_mub.py
> +async def create_task(community: CommunityById, data: Task.InputSchema) -> Task:
issue: Мы передаем `id` (просто число) сообщества, чтобы получить `community` с помощью зависимости `CommunityById`, чтобы использовать `community.id`. Достаточно просто получить `id` и использовать его

2024-06-19 11:05 UTC, niqzart commented on app/communities/models/tasks_db.py
> +            stmt.order_by(cls.creation_date)
Оператор `is` существует

2024-06-19 11:06 UTC, niqzart commented on app/communities/models/tasks_db.py
> +    WRITING = "writing"
tip: Смотрите на фронт и пользуйтесь переводчиком. В крайнем случае можно спрашивать, какой им нейминг нравится

2024-06-19 11:07 UTC, niqzart commented on app/communities/dependencies/tasks_dep.py
> +async def get_tasks_by_community_id(community: CommunityById) -> Sequence[Task]:
Очень странный suggestion, тут проблема в существовании этих dependency, а не в "лишних" данных

2024-06-19 11:09 UTC, niqzart commented on app/communities/models/tasks_db.py
> +            stmt.order_by(cls.creation_date)
https://docs.python.org/3/howto/enum.html#comparisons

2024-06-19 11:13 UTC, niqzart commented on app/communities/dependencies/tasks_dep.py
> +async def get_tasks_by_community_id(community: CommunityById) -> Sequence[Task]:
Это не значит, что проблемы нет, тут же всё на повехности...

2024-06-19 15:00 UTC, kinuser commented on app/communities/models/tasks_db.py
> +    InputSchema = MappedModel.create(
![image](https://github.com/xi-effect/xi.back-2/assets/94530532/e5da6e58-257c-4f6f-a648-20ef780aadd3)

2024-06-19 15:03 UTC, max31ru12 commented on app/communities/models/tasks_db.py
> +    InputSchema = MappedModel.create(
Это не форма. Тут мы не задаем время создания.

2024-06-19 17:03 UTC, kinuser commented on app/communities/models/tasks_db.py
> +    creation_date: Mapped[datetime] = mapped_column(DateTime(timezone=True))
@niqzart есть предпочтения, как хендлить разные часовые пояса?

2024-06-19 17:04 UTC, kinuser commented on app/communities/models/tasks_db.py
> +    async def get_paginated(  # noqa: WPS211
Как и зачем? @niqzart какие варианты решения тебе бы тут зашли

2024-06-19 17:04 UTC, kinuser commented on app/communities/models/tasks_db.py
> +            stmt.order_by(cls.creation_date)
Не очень понял suggestion

2024-06-19 17:04 UTC, kinuser commented on app/communities/routes/tasks_mub.py
> +    return tasks
Один из вариантов

2024-06-19 17:04 UTC, kinuser commented on app/communities/dependencies/tasks_dep.py
> +async def get_tasks_by_community_id(community: CommunityById) -> Sequence[Task]:
@max31ru12 Сначала написал так, потом переписал c зависимосями community, нужно спросить как @niqzart больше нравится

Идею о вынесении логики с ошибками в зависимости взял отсюда
https://github.com/xi-effect/xi.back-2/blob/981c8ca7e6d7e867638ce798560e30c2f3153777/app/communities/dependencies/communities_dep.py#L13-L18

2024-06-19 17:04 UTC, kinuser commented on app/communities/dependencies/tasks_dep.py
> +    community: CommunityById,
Тредик выше

2024-06-19 17:05 UTC, kinuser commented on app/communities/models/tasks_db.py
> +    WRITING = "writing"
Writing task - письменное задание

2024-06-19 17:05 UTC, kinuser commented on app/communities/models/tasks_db.py
> +            stmt.order_by(cls.creation_date)
Эта работает, т.к. в ordering приходит уже значение enum'а. Но я там забыл в другом месте кое что и уже пофиксил

2024-06-19 17:55 UTC, max31ru12 commented on app/communities/dependencies/tasks_dep.py
> +async def get_tasks_by_community_id(community: CommunityById) -> Sequence[Task]:
Существование этих зависимостей нарушает KISS, на мой взгляд. Больше проблем я не вижу

2024-06-19 18:01 UTC, max31ru12 commented on app/communities/models/tasks_db.py
> +    async def get_paginated(  # noqa: WPS211
Зачем: Потому что она есть и есть [способы ее решения](https://wemake-python-styleguide.readthedocs.io/en/latest/pages/usage/violations/complexity.html#wemake_python_styleguide.violations.complexity.TooManyArgumentsViolation)
Обрати внимание на строчку:
> This is an indicator of a bad design.

2024-06-19 18:03 UTC, max31ru12 commented on app/communities/models/tasks_db.py
> +            stmt.order_by(cls.creation_date)
Отмеченный кусок кода просто вынести в другое место, потому он решает задачу `фильтрации` в функции, решающей задачу `пагинации`. фильтрация `И` пагинация в контексте одной функции - это нарушение single responsibility

2024-06-19 18:05 UTC, max31ru12 commented on app/communities/dependencies/tasks_dep.py
> +    community: CommunityById,
Разберемся с тем, сделаю resolve и на этот коммент )

2024-06-19 18:07 UTC, max31ru12 commented on app/communities/models/tasks_db.py
> +            stmt.order_by(cls.creation_date)
Не, это все еще проблема. Каждый взгляд на этот участок кода будет из раза в раз вызывать вопросы, а также необходимо держать в голове, что в ordering необходимо передавать значение enum'а. Нужно сделать проще, иначе могут быть проблемы при дебаге

2024-06-19 18:34 UTC, niqzart commented on app/communities/models/tasks_db.py
> +    async def get_paginated(  # noqa: WPS211
Если можно решить, то было бы неплохо, но боюсь будет криво. Если решите всё же не решать, то WPS этот стоит закинуть в .flake8

2024-06-19 18:48 UTC, niqzart commented on app/communities/models/tasks_db.py
> +    creation_date: Mapped[datetime] = mapped_column(DateTime(timezone=True))
Варианты?

2024-06-19 18:49 UTC, niqzart commented on app/communities/dependencies/tasks_dep.py
> +async def get_tasks_by_community_id(community: CommunityById) -> Sequence[Task]:
> Идею о вынесении логики с ошибками в зависимости взял отсюда

Там и тут ноль общего

2024-06-19 18:49 UTC, niqzart commented on app/communities/models/tasks_db.py
> +    WRITING = "writing"
Кто сказал, что оно так назвается

2024-06-19 18:56 UTC, niqzart commented on app/communities/routes/tasks_mub.py
> +    return tasks
Это реализуется через query-параметры, да

2024-06-19 19:29 UTC, kinuser commented on app/communities/models/tasks_db.py
> +    creation_date: Mapped[datetime] = mapped_column(DateTime(timezone=True))
Часовой пояс будет привязываться к клиенту? Если да, то кто его привяжет - фронт или бек?

2024-06-19 19:29 UTC, kinuser commented on app/communities/models/tasks_db.py
> +    InputSchema = MappedModel.create(
На фронт для заполнения вот этой страницы нужно выслать в том числе поле с датой создания

2024-06-19 19:30 UTC, kinuser commented on app/communities/models/tasks_db.py
> +    async def get_paginated(  # noqa: WPS211
Для меня не проблема, если в функции будет больше 5 аргументов. Думаю в принципе рекомендация хорошая, но не всегда применимая

2024-06-19 19:30 UTC, kinuser commented on app/communities/models/tasks_db.py
> +            stmt.order_by(cls.creation_date)
Обычно в функции выносят повторяющуюся логику. SOLID - набор абстрактных рекомендаций, но не абсолютный гайд как правильно писать код

2024-06-19 19:31 UTC, kinuser commented on app/communities/models/tasks_db.py
> +            stmt.order_by(cls.creation_date)
Как бы ты решил?

2024-06-19 19:37 UTC, max31ru12 commented on app/communities/models/tasks_db.py
> +    async def get_paginated(  # noqa: WPS211
Если вынести фильтрацию из этого метода, то уйдет параметр `ordering`. Это решит сразу две проблемы. 
`Для меня это не проблема` - это недостаточная аргументация

2024-06-19 19:40 UTC, max31ru12 commented on app/communities/models/tasks_db.py
> +    InputSchema = MappedModel.create(
У тебя для создания таски используется InputSchema, для выдачи на фронт - ResponseSchema. Я абсолютно не понимаю, зачем здесь передавать время создания таски для создания таски.

2024-06-19 19:45 UTC, max31ru12 commented on app/communities/models/tasks_db.py
> +    creation_date: Mapped[datetime] = mapped_column(DateTime(timezone=True))
Кажется, мы использовали utcnow(). ИМХО фронт должен быть ответственен за показываемое клиенту время, потому что если учитель и ученик будут в разных часовых поясах, то время создания таски для будет разное. Например, учитель создаст таску в 13:00 будущем, а у ученика сейчас 12:00. Таска для ученика создана в будущем.

2024-06-19 20:03 UTC, niqzart commented on app/communities/models/tasks_db.py
> +    creation_date: Mapped[datetime] = mapped_column(DateTime(timezone=True))
Скопированно из дискорда:

> Вы что совсем не знаете как timezone-aware datetime работает?
> Если в нём указана таймзона то всё, оно автоматически правильное для всех
utcnow() или now(tz=timezone.utc) выдаёт текущее время относительно UTC. Если сейчас 13:00 МСК, то он выдаст 10:00 UTC
Если учитель в МСК и ему придёт 10:00 UTC, то фронт отобразит 13:00. Если ученик в UTC+4:30, то фронт отобразит 14:30
Бэк при этом хранит date + time + timezone

2024-06-19 20:05 UTC, niqzart commented on app/communities/models/tasks_db.py
> +    async def get_paginated(  # noqa: WPS211
Звучит криво

2024-06-19 20:29 UTC, kinuser commented on app/communities/models/tasks_db.py
> +    InputSchema = MappedModel.create(
Зону спрашивает у клиента фронт, затем отправляет нам время с зоной.  По крайней мере я это так себе представлял

2024-06-19 20:38 UTC, kinuser commented on app/communities/dependencies/tasks_dep.py
> +async def get_tasks_by_community_id(community: CommunityById) -> Sequence[Task]:
@max31ru12 ну я тогда закастую DRY)
@niqzart  6 строчек одинакового кода 0_0

P.S. Я в эти строчки сильно эмоционально не вдаюсь, если что, то последнее слово за @niqzart

2024-06-19 20:44 UTC, max31ru12 commented on app/communities/models/tasks_db.py
> +            stmt.order_by(cls.creation_date)
Я с тобой согласен. Однако, этих рекомендаций придерживается большинство программистов. И если что-то идет в разрез с этими рекомендациями, то должна быть причина, почему это делается так или иначе

2024-06-19 20:55 UTC, max31ru12 commented on app/communities/models/tasks_db.py
> +            stmt.order_by(cls.creation_date)
Наверное,`if ordering is TaskOrdering.CLOSING_DATE:`, а передачу в аргументах enum'а оставил бы

2024-06-20 16:03 UTC, niqzart commented on app/communities/models/tasks_db.py
> +    InputSchema = MappedModel.create(
Это так, но к дате создания не относится

2024-09-07 21:28 UTC, niqzart commented
Closed in favour of #24

2024-09-07 21:28 UTC, closed without merging