TMEXIO start
xi-effect/xi.back-2 pull request #5
Opened 2024-05-12 16:32 UTC by niqzart

2024-08-28 13:14 UTC, max31ru12 requested changes

2024-08-28 13:14 UTC, max31ru12 commented on app/communities/dependencies/communities_sio_dep.py
> +async def community_by_id_dependency(community_id: int) -> Community:
issue: Неконсистентное название `community_by_id_dependency`
suggestion: `get_community_by_id`, как у тебя в коде выше

2024-08-28 13:14 UTC, max31ru12 commented on app/communities/dependencies/communities_sio_dep.py
> +async def current_participant_dependency(
issue: Аналогично - неконсистентность
suggestion: Аналогично через `get...`

2024-08-28 13:19 UTC, niqzart commented on app/common/dependencies/authorization_dep.py
> +    # may raise pydantic.ValidationError
Не, это решено обработкой в `authorize_proxy`, прост mypy ругается, я пояснил, почему использую type: ignore

2024-08-28 13:20 UTC, niqzart commented on app/common/dependencies/authorization_sio_dep.py
> +def header_to_wsgi_var(header_name: str) -> str:
Есть такое, но проблема в том, что это термин https://peps.python.org/pep-3333/#environ-variables

2024-08-28 13:21 UTC, niqzart commented on app/communities/dependencies/categories_sio_dep.py
> +async def get_category_by_ids(
Категория в единственном числе (category), во множественном тут ids, потому что idшников несколько
![image](https://github.com/user-attachments/assets/7ba2dacb-8fb8-4567-8a96-12c61770c067)

2024-08-28 13:21 UTC, niqzart commented on app/communities/dependencies/channels_sio_dep.py
> +async def get_channel_by_ids(  # TODO (37570606) pragma: no cover
Аналогично))

2024-08-28 13:21 UTC, niqzart commented on app/communities/dependencies/communities_sio_dep.py
> +async def community_by_id_dependency(community_id: int) -> Community:
Fair, поправлю

2024-08-28 13:25 UTC, max31ru12 commented on app/common/dependencies/authorization_sio_dep.py
> +def header_to_wsgi_var(header_name: str) -> str:
Тогда `issue` плавно перетекает в `suggestion`. Мб стоит сделать какую-то поясняющую doc-строку, что думаешь?

2024-08-28 13:28 UTC, max31ru12 commented on app/communities/dependencies/categories_sio_dep.py
> +async def get_category_by_ids(
Почему по идентификаторАМ, если в функцию мы передаем индентификатОР? А затем производим поиск с помощью метода `find_first_by_id`? Может я что-то упустил?

2024-08-28 13:32 UTC, niqzart commented on app/communities/dependencies/categories_sio_dep.py
> +async def get_category_by_ids(
Там ещё community используется из фикстуры. Хотелось в нейминге отметить, что проверка не только категории, но и сущности выше

2024-08-28 13:38 UTC, max31ru12 commented on app/communities/dependencies/categories_sio_dep.py
> +async def get_category_by_ids(
Ты думаешь, что название функции передает то, что ты хотел отметить?

2024-08-28 14:13 UTC, niqzart commented on app/communities/dependencies/categories_sio_dep.py
> +async def get_category_by_ids(
Это просто на случай, если будет штука, которая будет получать категорию без получения community

2024-08-28 14:14 UTC, niqzart commented on app/communities/dependencies/categories_sio_dep.py
> +async def get_category_by_ids(
Обрати задание на `category.community_id != community.id`, по моей логике это уже не просто by_id. Но может можно иначе обозвать? Или пофиг, by_id?

2024-08-28 14:18 UTC, max31ru12 commented on app/communities/dependencies/categories_sio_dep.py
> +async def get_category_by_ids(
by_id точно недостаточно. Напрашивается by_id_and_community, но это явно плохой вариант. Стоит еще подумать, но если ничего лучше не придумается, то либо doc-строку, либо поясняющий комментарий стоит оставить

2024-08-31 12:58 UTC, niqzart commented on app/communities/dependencies/categories_sio_dep.py
> +async def get_category_by_ids(
В комментарии смысла нет, это зло

2024-08-31 13:01 UTC, niqzart commented on app/communities/dependencies/categories_sio_dep.py
> +async def get_category_by_ids(
Нейминг он для использующего, а использующий этот dependency человек будет понимать, что category получается по нескольким idшникам, точнее всем id, что вообще есть у категории. Всё логично

2024-08-31 17:46 UTC, max31ru12 approved these changes

2024-08-31 17:58 UTC, merged